Docker Requirement handling
daytonaio/daytona-provider-docker pull request #41
Opened 2024-10-28 09:14 UTC by Philip-21

## Description

Docker requirement handling checks before daytona server runs. This adds validation checks to ensure the required OS meets the docker requirements before spinning up daytona server

This PR addresses [issue](https://github.com/daytonaio/daytona/issues/673) in the daytona codebase, and it requires the [pr](https://github.com/daytonaio/daytona/pull/1300), to get merged as various the requirement type objects are used in the docker provider.

I ran it locally by following the build [process](https://github.com/daytonaio/daytona/tree/main/pkg/docker#testing) and it was successful

2024-10-28 10:05 UTC, Tpuljak requested changes

2024-10-28 10:05 UTC, Tpuljak commented on open-source/daytona-provider-docker/docker-provider
Remove this file from the PR

2024-10-28 11:45 UTC, Philip-21 commented on open-source/daytona-provider-docker/docker-provider
Ow yh i will, i forgot to remove it

2024-10-28 12:00 UTC, Philip-21 commented on open-source/daytona-provider-docker/docker-provider
@Tpuljak its been removed

2024-11-04 11:17 UTC, Tpuljak requested changes

2024-11-04 11:17 UTC, Tpuljak commented on pkg/provider/provider.go
> +			Reason: "Docker is not running.",
Leave this in so the user knows the exact problem

2024-11-04 12:09 UTC, Philip-21 commented on pkg/provider/provider.go
> +			Reason: "Docker is not running. Error: " + err.Error(),
Yes i have added it back

2024-11-22 12:16 UTC, Tpuljak approved these changes

2024-11-22 12:16 UTC, merged